# Generated by Django 6.0.2 on 2026-02-21 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('notification_type', models.CharField(choices=[('lesson_reminder', '🔔 Напоминание о занятии'), ('lesson_canceled', '❌ Занятие отменено'), ('lesson_completed', '✅ Занятие проведено'), ('payment_received', '💰 Поступление средств'), ('payment_withdrawn', '💸 Списание средств'), ('material_added', '📚 Новый материал'), ('homework_assigned', '📝 Новое задание'), ('system', '⚙ Системное уведомление')], default='system', max_length=20, verbose_name='Тип уведомления')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='school_noti_user_id_e6b623_idx'), models.Index(fields=['user', 'is_read'], name='school_noti_user_id_ca5454_idx')],
            },
        ),
    ]
