# Generated by Django 6.0.2 on 2026-02-21 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('lesson_reminder', '🔔 Напоминание о занятии'), ('lesson_canceled', '❌ Занятие отменено'), ('lesson_completed', '✅ Занятие проведено'), ('payment_received', '💰 Поступление средств'), ('payment_withdrawn', '💸 Списание средств'), ('material_added', '📚 Новый материал'), ('homework_assigned', '📝 Новое задание'), ('feedback_received', '⭐ Новая оценка'), ('system', '⚙ Системное уведомление')], default='system', max_length=20, verbose_name='Тип уведомления'),
        ),
        migrations.CreateModel(
            name='TeacherRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.FloatField(default=0, verbose_name='Средний балл')),
                ('total_feedbacks', models.IntegerField(default=0, verbose_name='Всего оценок')),
                ('rating_5_count', models.IntegerField(default=0, verbose_name='5⭐')),
                ('rating_4_count', models.IntegerField(default=0, verbose_name='4⭐')),
                ('rating_3_count', models.IntegerField(default=0, verbose_name='3⭐')),
                ('rating_2_count', models.IntegerField(default=0, verbose_name='2⭐')),
                ('rating_1_count', models.IntegerField(default=0, verbose_name='1⭐')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_stats', to='school.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Рейтинг учителя',
                'verbose_name_plural': 'Рейтинги учителей',
            },
        ),
        migrations.CreateModel(
            name='LessonFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '⭐ Ужасно'), (2, '⭐⭐ Плохо'), (3, '⭐⭐⭐ Нормально'), (4, '⭐⭐⭐⭐ Хорошо'), (5, '⭐⭐⭐⭐⭐ Отлично')], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, help_text='Что понравилось? Что можно улучшить?', verbose_name='Комментарий')),
                ('is_public', models.BooleanField(default=False, help_text='Показывать на сайте?', verbose_name='Публичный отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='school.lesson', verbose_name='Урок')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='school.student', verbose_name='Ученик')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='school.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Оценка урока',
                'verbose_name_plural': 'Оценки уроков',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', '-created_at'], name='school_less_teacher_5a8524_idx'), models.Index(fields=['student', '-created_at'], name='school_less_student_7bee19_idx'), models.Index(fields=['rating'], name='school_less_rating_90c6f1_idx')],
            },
        ),
    ]
