# Generated by Django 5.2.11 on 2026-02-26 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='school.payment'),
        ),
    ]
