# Generated by Django 6.0.2 on 2026-02-21 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_notification_notification_type_teacherrating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('lesson_reminder', '🔔 Напоминание о занятии'), ('lesson_canceled', '❌ Занятие отменено'), ('lesson_completed', '✅ Занятие проведено'), ('payment_received', '💰 Поступление средств'), ('payment_withdrawn', '💸 Списание средств'), ('material_added', '📚 Новый материал'), ('homework_assigned', '📝 Новое задание'), ('feedback_received', '⭐ Новая оценка'), ('system', '⚙ Системное уведомление'), ('homework_assigned', '📝 Новое задание'), ('homework_submitted', '📤 Задание сдано'), ('homework_checked', '✅ Задание проверено')], default='system', max_length=20, verbose_name='Тип уведомления'),
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='homeworks/attachments/', verbose_name='Файл с заданием')),
                ('deadline', models.DateTimeField(verbose_name='Срок сдачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='school.lesson', verbose_name='Урок')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='school.student', verbose_name='Ученик')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_homeworks', to='school.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, verbose_name='Текст ответа')),
                ('file', models.FileField(blank=True, null=True, upload_to='homeworks/submissions/', verbose_name='Файл с работой')),
                ('status', models.CharField(choices=[('submitted', 'Отправлено на проверку'), ('checked', 'Проверено')], default='submitted', max_length=20, verbose_name='Статус')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий учителя')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата сдачи')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='school.homework', verbose_name='Задание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='school.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Выполненное задание',
                'verbose_name_plural': 'Выполненные задания',
            },
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['student', 'deadline'], name='school_home_student_9a79ca_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['teacher', '-created_at'], name='school_home_teacher_1bda42_idx'),
        ),
    ]
