# Generated by Django 5.2.11 on 2026-02-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_lesson_status_deposit_material_studentnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='rescheduled_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Перенесено с'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='rescheduled_reason',
            field=models.TextField(blank=True, verbose_name='Причина переноса'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='rescheduled_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Перенесено на'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланировано'), ('completed', 'Проведено'), ('cancelled', 'Отменено'), ('no_show', 'Ученик не явился'), ('overdue', 'Просрочено'), ('rescheduled', 'Перенесено')], default='scheduled', max_length=20, verbose_name='Статус'),
        ),
    ]
