# Generated by Django 5.2.11 on 2026-02-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_notification_notification_type_homework_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonreport',
            name='video_room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
