# Generated by Django 5.2.11 on 2026-02-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_lessonreport_video_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonreport',
            name='video_room',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_room',
            field=models.CharField(blank=True, help_text='Уникальный идентификатор комнаты для Jitsi Meet', max_length=100, null=True, verbose_name='Комната для видео'),
        ),
    ]
