# Generated by Django 5.2.11 on 2026-02-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_useractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_notifications',
            field=models.BooleanField(default=False, verbose_name='Получать уведомления в Telegram'),
        ),
    ]
