# Generated by Django 5.2.11 on 2026-02-21 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_lessonreport_video_room_lesson_video_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('duration', models.IntegerField(default=60, verbose_name='Длительность (минут)')),
                ('price_type', models.CharField(choices=[('fixed', 'Фиксированная за группу'), ('per_student', 'За каждого ученика')], default='per_student', max_length=20, verbose_name='Тип оплаты')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Для per_student: цена за одного, для fixed: цена за всю группу', max_digits=10, verbose_name='Базовая стоимость')),
                ('teacher_payment', models.DecimalField(decimal_places=2, help_text='Базовая выплата (может корректироваться в зависимости от числа учеников)', max_digits=10, verbose_name='Выплата учителю')),
                ('meeting_link', models.URLField(blank=True, verbose_name='Ссылка на занятие')),
                ('meeting_platform', models.CharField(blank=True, max_length=50, verbose_name='Платформа')),
                ('video_room', models.CharField(blank=True, max_length=100, null=True, verbose_name='Комната для видео')),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('completed', 'Проведено'), ('cancelled', 'Отменено'), ('no_show', 'Ученик не явился'), ('overdue', 'Просрочено'), ('rescheduled', 'Перенесено')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.lessonformat', verbose_name='Формат')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_lessons', to='school.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Групповое занятие',
                'verbose_name_plural': 'Групповые занятия',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='group_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_lessons', to='school.grouplesson', verbose_name='Групповое занятие'),
        ),
        migrations.CreateModel(
            name='GroupEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_to_pay', models.DecimalField(decimal_places=2, help_text='Может отличаться от базовой (скидка, акция)', max_digits=10, verbose_name='Стоимость для ученика')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка %')),
                ('status', models.CharField(choices=[('registered', 'Зарегистрирован'), ('attended', 'Присутствовал'), ('absent', 'Отсутствовал'), ('debt', 'Задолженность')], default='registered', max_length=20, verbose_name='Статус')),
                ('attendance_confirmed', models.BooleanField(default=False, verbose_name='Посещение подтверждено')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирован')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_enrollments', to='school.student', verbose_name='Ученик')),
                ('group_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='school.grouplesson', verbose_name='Групповое занятие')),
            ],
            options={
                'verbose_name': 'Запись на группу',
                'verbose_name_plural': 'Записи на группы',
                'unique_together': {('group_lesson', 'student')},
            },
        ),
    ]
