# Generated by Django 5.2.11 on 2026-02-21 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_grouplesson_lesson_group_lesson_groupenrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='group_lesson',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='student',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher_payment',
        ),
        migrations.AddField(
            model_name='lesson',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Базовая стоимость'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='base_teacher_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Базовая выплата учителю'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_group',
            field=models.BooleanField(default=False, verbose_name='Групповой урок'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Фиксированная за всех'), ('per_student', 'За каждого ученика'), ('individual', 'Индивидуальная для каждого')], default='per_student', max_length=20, verbose_name='Тип оплаты'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='student_old',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_old', to='school.student', verbose_name='Ученик (старое поле)'),
        ),
        migrations.CreateModel(
            name='LessonAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость для ученика')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка %')),
                ('teacher_payment_share', models.DecimalField(decimal_places=2, help_text='Сколько учитель получает за этого ученика', max_digits=10, verbose_name='Доля выплаты учителю')),
                ('status', models.CharField(choices=[('registered', 'Зарегистрирован'), ('attended', 'Присутствовал'), ('absent', 'Отсутствовал'), ('debt', 'Задолженность')], default='registered', max_length=20, verbose_name='Статус')),
                ('attendance_confirmed', models.BooleanField(default=False, verbose_name='Посещение подтверждено')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирован')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='school.lesson', verbose_name='Урок')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_attendance', to='school.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Посещаемость урока',
                'verbose_name_plural': 'Посещаемость уроков',
                'unique_together': {('lesson', 'student')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(related_name='lessons', through='school.LessonAttendance', to='school.student', verbose_name='Ученики'),
        ),
    ]
