# Generated by Django 5.2.11 on 2026-02-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_user_telegram_chat_id_user_telegram_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_notifications',
            field=models.BooleanField(default=False, help_text='Отправлять уведомления о уроках, платежах и т.д.', verbose_name='Получать уведомления в Telegram'),
        ),
    ]
