# Generated by Django 5.2.11 on 2026-02-22 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_remove_lesson_cost_remove_lesson_group_lesson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('duration', models.IntegerField(default=60, editable=False, verbose_name='Длительность (минут)')),
                ('repeat_type', models.CharField(choices=[('daily', 'Каждый день'), ('weekly', 'Каждую неделю'), ('biweekly', 'Раз в две недели'), ('monthly', 'Каждый месяц')], default='weekly', max_length=20, verbose_name='Тип повторения')),
                ('monday', models.BooleanField(default=False, verbose_name='Понедельник')),
                ('tuesday', models.BooleanField(default=False, verbose_name='Вторник')),
                ('wednesday', models.BooleanField(default=False, verbose_name='Среда')),
                ('thursday', models.BooleanField(default=False, verbose_name='Четверг')),
                ('friday', models.BooleanField(default=False, verbose_name='Пятница')),
                ('saturday', models.BooleanField(default=False, verbose_name='Суббота')),
                ('sunday', models.BooleanField(default=False, verbose_name='Воскресенье')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, help_text='Оставьте пустым для бесконечного повторения', null=True, verbose_name='Дата окончания')),
                ('max_occurrences', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальное количество занятий')),
                ('base_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Базовая стоимость')),
                ('base_teacher_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Базовая выплата учителю')),
                ('price_type', models.CharField(choices=[('fixed', 'Фиксированная за всех'), ('per_student', 'За каждого ученика'), ('individual', 'Индивидуальная для каждого')], default='per_student', max_length=20, verbose_name='Тип оплаты')),
                ('meeting_link', models.URLField(blank=True, verbose_name='Ссылка на занятие')),
                ('meeting_platform', models.CharField(blank=True, max_length=50, verbose_name='Платформа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.lessonformat', verbose_name='Формат')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to='school.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Шаблон расписания',
                'verbose_name_plural': 'Шаблоны расписания',
            },
        ),
        migrations.CreateModel(
            name='ScheduleTemplateStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Индивидуальная стоимость')),
                ('individual_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Индивидуальная выплата')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to='school.student')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_settings', to='school.scheduletemplate')),
            ],
            options={
                'verbose_name': 'Настройка ученика в шаблоне',
                'verbose_name_plural': 'Настройки учеников в шаблоне',
                'unique_together': {('template', 'student')},
            },
        ),
        migrations.AddField(
            model_name='scheduletemplate',
            name='students',
            field=models.ManyToManyField(through='school.ScheduleTemplateStudent', to='school.student', verbose_name='Ученики'),
        ),
    ]
