# Generated by Django 5.2.11 on 2026-02-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_add_telegram_fields_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID чата для отправки уведомлений (например: 1226934902)', max_length=100, null=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_notifications',
            field=models.BooleanField(default=False, help_text='Отправлять уведомления о новых уроках, платежах и т.д.', verbose_name='Получать уведомления в Telegram'),
        ),
    ]
