# Generated by Django 5.2.11 on 2026-03-01 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_user_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Способ выплаты')),
                ('payment_details', models.TextField(verbose_name='Платёжные реквизиты')),
                ('status', models.CharField(choices=[('pending', '⏳ Ожидает'), ('approved', '✅ Одобрено'), ('rejected', '❌ Отклонено'), ('paid', '💰 Выплачено')], default='pending', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, help_text='Комментарий администратора', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_request', to='school.payment', verbose_name='Платеж')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='school.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Запрос выплаты',
                'verbose_name_plural': 'Запросы выплат',
                'ordering': ['-created_at'],
            },
        ),
    ]
