# Generated by Django 5.2.11 on 2026-02-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_scheduletemplate_scheduletemplatestudent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletemplate',
            name='base_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Базовая стоимость'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='base_teacher_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Базовая выплата учителю'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='price_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Фиксированная за всех'), ('per_student', 'За каждого ученика'), ('individual', 'Индивидуальная для каждого')], default='per_student', max_length=20, null=True, verbose_name='Тип оплаты'),
        ),
    ]
