# Generated by Django 5.2.11 on 2026-02-22 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_scheduletemplate_base_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjectPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Сколько платит ученик', max_digits=10, verbose_name='Стоимость урока')),
                ('teacher_payment', models.DecimalField(decimal_places=2, help_text='Сколько получает учитель', max_digits=10, verbose_name='Выплата учителю')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Скидка %')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_prices', to='school.student', verbose_name='Ученик')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Цена для ученика',
                'verbose_name_plural': 'Цены для учеников',
                'ordering': ['student', 'subject'],
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
