# Generated by Django 5.2.11 on 2026-03-11 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_studentsubjectprice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('role', models.CharField(blank=True, help_text='Например: мама Таира (8 лет), 29 лет, г. Санкт-Петербург', max_length=100, verbose_name='Роль')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='feedback/', verbose_name='Фото')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 ★'), (2, '2 ★'), (3, '3 ★'), (4, '4 ★'), (5, '5 ★')], default=5, verbose_name='Оценка')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать на сайте', verbose_name='Активен')),
                ('is_on_main', models.BooleanField(default=True, help_text='Показывать в карусели на главной', verbose_name='На главной')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('teacher', models.ForeignKey(blank=True, help_text='Если отзыв о конкретном учителе', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
