# Generated by Django 5.2.11 on 2026-02-23 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_emailverificationtoken_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduletemplate',
            name='price_type',
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='base_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Базовая стоимость'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='base_teacher_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Базовая выплата учителю'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.lessonformat'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='repeat_type',
            field=models.CharField(choices=[('single', 'Разовый урок'), ('daily', 'Каждый день'), ('weekly', 'Каждую неделю'), ('biweekly', 'Раз в две недели'), ('monthly', 'Каждый месяц')], default='single', max_length=20, verbose_name='Тип повторения'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='students',
            field=models.ManyToManyField(blank=True, through='school.ScheduleTemplateStudent', to='school.student'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to='school.teacher'),
        ),
    ]
