# Generated by Django 5.2.11 on 2026-03-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['team_sort_order', 'user__last_name'], 'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='show_on_team',
            field=models.BooleanField(default=True, help_text='Отображать учителя на странице /team/', verbose_name='Показывать в команде'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='team_description',
            field=models.TextField(blank=True, help_text='Краткое описание для карточки (если не заполнено, используется bio)', verbose_name='Описание для страницы команды'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='team_highlight',
            field=models.BooleanField(default=False, help_text='Поместить в топ или выделить специальным образом', verbose_name='Выделить на странице'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='team_photo',
            field=models.ImageField(blank=True, help_text='Если не указано, используется основное фото', null=True, upload_to='teachers/team/', verbose_name='Фото для команды'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='team_sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Меньше число = выше в списке', verbose_name='Порядок в команде'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='telegram_url',
            field=models.URLField(blank=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='vk_url',
            field=models.URLField(blank=True, verbose_name='VK'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='whatsapp_url',
            field=models.URLField(blank=True, verbose_name='WhatsApp'),
        ),
    ]
