# Generated by Django 5.2.11 on 2026-02-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_remove_scheduletemplate_price_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletemplate',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
    ]
