# Generated by Django 5.2.11 on 2026-03-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_alter_teacher_options_teacher_instagram_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='team_photo',
        ),
    ]
