# Generated by Django 5.2.11 on 2026-02-23 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_scheduletemplate_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletemplate',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.lessonformat', verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='students',
            field=models.ManyToManyField(blank=True, through='school.ScheduleTemplateStudent', to='school.student', verbose_name='Ученики'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to='school.teacher', verbose_name='Учитель'),
        ),
    ]
