# Generated by Django 5.2.11 on 2026-03-22 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_remove_teacher_team_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, help_text='Автоматически создается из заголовка. Можно изменить вручную.', max_length=200, unique=True, verbose_name='URL')),
                ('content', models.TextField(help_text='Основной текст статьи (поддерживает HTML)', verbose_name='Текст статьи')),
                ('photo', models.ImageField(blank=True, help_text='Главное изображение для статьи', null=True, upload_to='articles/', verbose_name='Основное фото')),
                ('author', models.CharField(blank=True, default='Плюс Прогресс', max_length=100, verbose_name='Автор')),
                ('excerpt', models.CharField(blank=True, help_text='Показывается в списке статей', max_length=300, verbose_name='Краткое описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('is_featured', models.BooleanField(default=False, help_text='Показывать в виджете "Рекомендуемые статьи"', verbose_name='Рекомендуемая')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='school_arti_slug_b69c01_idx'), models.Index(fields=['-created_at'], name='school_arti_created_9cbeb2_idx'), models.Index(fields=['is_published', '-created_at'], name='school_arti_is_publ_e35bd7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArticleAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('attachment_type', models.CharField(choices=[('file', 'Файл'), ('link', 'Ссылка')], default='file', max_length=10, verbose_name='Тип')),
                ('file', models.FileField(blank=True, null=True, upload_to='articles/attachments/', verbose_name='Файл')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('allow_download', models.BooleanField(default=True, help_text='Если отключено, файл можно только просматривать в браузере', verbose_name='Разрешить скачивание')),
                ('is_embedded', models.BooleanField(default=False, help_text='Для изображений и PDF - показывать прямо на странице', verbose_name='Встраивать на страницу')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='school.article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
