# Generated by Django 5.2.11 on 2026-05-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_article_articleattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='action_type',
            field=models.CharField(choices=[('login', '🔐 Вход в систему'), ('logout', '🔒 Выход из системы'), ('calendar_export', '📄 Экспорт календаря'), ('lesson_view', '👁️ Просмотр урока'), ('lesson_edit', '✏️ Редактирование урока'), ('lesson_create', '➕ Создание урока'), ('lesson_complete', '✅ Завершение урока'), ('homework_view', '📚 Просмотр ДЗ'), ('homework_submit', '📤 Сдача ДЗ'), ('payment_view', '💰 Просмотр платежей'), ('material_download', '⬇️ Скачивание материала'), ('video_room_enter', '🎥 Вход в видео-комнату'), ('profile_edit', '👤 Редактирование профиля'), ('report_view', '📊 Просмотр отчета'), ('other', '📌 Другое'), ('page_view', '👁️ Просмотр страницы')], max_length=30, verbose_name='Тип действия'),
        ),
    ]
