# Generated by Django 5.2.11 on 2026-07-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_alter_useractionlog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialrequest',
            name='honeypot_triggered',
            field=models.BooleanField(default=False, verbose_name='Honeypot сработал'),
        ),
        migrations.AddField(
            model_name='trialrequest',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес'),
        ),
        migrations.AddField(
            model_name='trialrequest',
            name='is_spam',
            field=models.BooleanField(default=False, verbose_name='Спам'),
        ),
        migrations.AddField(
            model_name='trialrequest',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
        migrations.AddField(
            model_name='trialrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки'),
        ),
        migrations.AddField(
            model_name='trialrequest',
            name='status',
            field=models.CharField(choices=[('new', '🆕 Новая'), ('processed', '✅ Обработана'), ('spam', '🚫 Спам'), ('duplicate', '🔄 Дубликат')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='trialrequest',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='trialrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddIndex(
            model_name='trialrequest',
            index=models.Index(fields=['email'], name='school_tria_email_e94601_idx'),
        ),
        migrations.AddIndex(
            model_name='trialrequest',
            index=models.Index(fields=['phone'], name='school_tria_phone_404173_idx'),
        ),
        migrations.AddIndex(
            model_name='trialrequest',
            index=models.Index(fields=['ip_address'], name='school_tria_ip_addr_8b065f_idx'),
        ),
        migrations.AddIndex(
            model_name='trialrequest',
            index=models.Index(fields=['status'], name='school_tria_status_8977fe_idx'),
        ),
    ]
