# Generated by Django 5.2.11 on 2026-08-03 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_trialrequest_honeypot_triggered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('max', 'Max (чат-боты)'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('viber', 'Viber'), ('vk', 'VK')], default='max', max_length=20, verbose_name='Платформа')),
                ('bot_name', models.CharField(help_text='Название бота в Max', max_length=100, verbose_name='Имя бота')),
                ('bot_id', models.CharField(help_text='Уникальный идентификатор бота', max_length=100, verbose_name='ID бота')),
                ('api_key', models.CharField(blank=True, help_text='API ключ для авторизации', max_length=255, verbose_name='API ключ')),
                ('webhook_url', models.URLField(blank=True, help_text='URL для входящих сообщений', verbose_name='Webhook URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notify_on_trial_request', models.BooleanField(default=True, verbose_name='Уведомлять о заявках')),
                ('notify_on_payment', models.BooleanField(default=True, verbose_name='Уведомлять о платежах')),
                ('notify_on_lesson', models.BooleanField(default=True, verbose_name='Уведомлять об уроках')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройка бота',
                'verbose_name_plural': 'Настройки ботов',
            },
        ),
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('incoming', 'Входящее'), ('outgoing', 'Исходящее')], max_length=10, verbose_name='Направление')),
                ('sender', models.CharField(blank=True, max_length=255, verbose_name='Отправитель')),
                ('recipient', models.CharField(blank=True, max_length=255, verbose_name='Получатель')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('response', models.TextField(blank=True, verbose_name='Ответ')),
                ('status', models.CharField(default='sent', max_length=50, verbose_name='Статус')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='school.botconfig')),
            ],
            options={
                'verbose_name': 'Сообщение бота',
                'verbose_name_plural': 'Сообщения ботов',
                'ordering': ['-created_at'],
            },
        ),
    ]
