# Generated by Django 5.2.11 on 2026-08-04 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_botconfig_botmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_chat_id',
            field=models.CharField(blank=True, help_text='ID пользователя в MAX для отправки уведомлений', max_length=100, null=True, verbose_name='MAX Chat ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='max_notifications',
            field=models.BooleanField(default=False, help_text='Отправлять уведомления через бота в MAX', verbose_name='Получать уведомления в MAX'),
        ),
        migrations.CreateModel(
            name='BotSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, unique=True, verbose_name='Chat ID')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Username')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Подписался')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_subscriber', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписчик бота',
                'verbose_name_plural': 'Подписчики бота',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
