# Generated by Django 5.2.11 on 2026-02-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trialrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на пробный урок', 'verbose_name_plural': 'Заявки на пробный урок'},
        ),
        migrations.AlterField(
            model_name='grouplesson',
            name='teacher_payment',
            field=models.DecimalField(decimal_places=2, help_text='Базовая выплата (может корректироваться в зависимости от числа учеников)', max_digits=10, verbose_name='Начисление учителю'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('income', 'Пополнение'), ('expense', 'Списание'), ('teacher_payment', 'Начисление учителю'), ('teacher_salary', 'Зарплата учителя')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='studentsubjectprice',
            name='teacher_payment',
            field=models.DecimalField(decimal_places=2, help_text='Сколько получает учитель', max_digits=10, verbose_name='Начисление учителю'),
        ),
    ]
