# Generated by Django 5.2.11 on 2026-02-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_notification_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('income', 'Пополнение'), ('expense', 'Списание'), ('teacher_salary', 'Зарплата учителя')], max_length=20, verbose_name='Тип'),
        ),
    ]
