# Generated by Django 5.2.11 on 2026-02-27 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_payment_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', '🔐 Вход в систему'), ('logout', '🔒 Выход из системы'), ('calendar_export', '📄 Экспорт календаря'), ('lesson_view', '👁️ Просмотр урока'), ('lesson_edit', '✏️ Редактирование урока'), ('lesson_create', '➕ Создание урока'), ('lesson_complete', '✅ Завершение урока'), ('homework_view', '📚 Просмотр ДЗ'), ('homework_submit', '📤 Сдача ДЗ'), ('payment_view', '💰 Просмотр платежей'), ('material_download', '⬇️ Скачивание материала'), ('video_room_enter', '🎥 Вход в видео-комнату'), ('profile_edit', '👤 Редактирование профиля'), ('report_view', '📊 Просмотр отчета'), ('other', '📌 Другое')], max_length=30, verbose_name='Тип действия')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='URL')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('object_type', models.CharField(blank=True, max_length=50, verbose_name='Тип объекта')),
                ('additional_data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог действия',
                'verbose_name_plural': 'Логи действий',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='school_user_user_id_77a689_idx'), models.Index(fields=['action_type', '-created_at'], name='school_user_action__0d58c8_idx'), models.Index(fields=['created_at'], name='school_user_created_e5b04e_idx')],
            },
        ),
    ]
