# Generated by Django 5.2.11 on 2026-03-02 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_homework_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentsubjectprice',
            options={'ordering': ['student', 'teacher', 'subject'], 'verbose_name': 'Цена для ученика', 'verbose_name_plural': 'Цены для учеников'},
        ),
        migrations.AlterUniqueTogether(
            name='studentsubjectprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentsubjectprice',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_prices', to='school.teacher', verbose_name='Учитель'),
        ),
        migrations.AlterUniqueTogether(
            name='studentsubjectprice',
            unique_together={('student', 'teacher', 'subject')},
        ),
    ]
